# Generated by Django 5.1.2 on 2024-12-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_image_post_image_1_post_image_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_2',
        ),
    ]
