# Generated by Django 5.1.2 on 2024-12-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_image_1_post_image_remove_post_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='additional_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
